line-length = 110
target-version = "py311"

extend-exclude = [".venv"]

[lint]
extend-select = [
    "ASYNC", # flake8-async
    "S",     # flake8-bandit
    "B",     # flake8-bugbear
    "A",     # flake8-builtins
    "C4",    # flake8-comprehensions
    "ERA",   # flake8-eradicate/eradicate
    "PIE",   # flake8-pie
    "T20",   # flake8-print
    "PT",    # flake8-pytest-style
    "SIM",   # flake8-simplify
    "TCH",   # flake8-type-checking
    "TID",   # flake8-tidy-imports

    "I",     # isort    
    "C90",   # mccabe
    "N",     # pep8-naming
    "PGH",   # pygrep
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "D",     # pydocstyle
    "UP",    # pyupgrade
    "PL",    # pylint
    "RUF"    # ruff checks
]

ignore = [
    # Whitespace before ':' not correctly handled in slices
    "E203",
    # Ignore pycodestyle's Missing Docstrings
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D213",
    # Async timeout
    "ASYNC109"
]

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
